name: Grocy Item Scanner
version: 1.0.0
slug: grocy_scanner
description: A Home Assistant addon for scanning items into Grocy.
arch:
  - amd64
  - armv7
  - aarch64
startup: application
init: false
protected: false
host_network: true
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 3456
webui: http://[HOST]:[PORT:3456]
options:
  grocy_api_key: ''
schema:
  grocy_api_key: str
