name: Grocy Item Scanner
version: 1.0.0
slug: grocy_scanner
description: Home Assistant addon to scan items into Grocy.
arch:
  - amd64
  - armv7
  - aarch64
startup: application
startup: application
protected: false
host_network: true
full_access: false
hassio_api: true
hassio_role: manager
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 3456
webui: http://[HOST]:[PORT:3456]
options:
  grocy_api_key: ""
schema:
  grocy_api_key: str
memory_limit: 256m
